x-common-env: &common-env
  SECRET: "FerreteriaSuperSecretaKeyParaTokens" 

services:

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761" 

  auth-service:
    build: ./auth-service
    ports:
      - "9096:9096"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  usuario-service:
    build: ./usuario-service
    ports:
      - "9092:9092"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  catalogo-service:
    build: ./catalogo-service
    ports:
      - "9091:9091"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  venta-service:
    build: ./venta-service
    ports:
      - "9094:9094"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  pedido-service:
    build: ./pedido-service
    ports:
      - "9098:9098"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  despacho-service:
    build: ./despacho-service
    ports:
      - "9095:9095"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  inventario-service:
    build: ./inventario-service
    ports:
      - "9093:9093"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  resena-service:
    build: ./resena-service
    ports:
      - "9097:9097"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  promocion-service:
    build: ./promocion-service
    ports:
      - "9099:9099"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "9090:9090"
    environment:
      <<: *common-env
    depends_on:
      - eureka-server
      - auth-service
      - usuario-service
      - catalogo-service
      - venta-service
      - pedido-service
      - despacho-service
      - inventario-service
      - resena-service
      - promocion-service