server:
  port: 9090

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: FerreteriaSuperSecretaKeyParaTokens

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/api/ventas/**

        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/api/productos/**

        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**

        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/api/inventario/**
            
        - id: despacho-service
          uri: lb://despacho-service
          predicates:
            - Path=/api/despachos/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/