# Nombre clave para que el Gateway lo encuentre después
spring.application.name=usuario-service

# ==========================================
# 1. CONFIGURACIÓN DEL SERVIDOR Y NOMBRE
# ==========================================
# Asignamos el puerto 9092 como acordamos
server.port=9092

# ==========================================
# 2. CONEXIÓN A LA BASE DE DATOS (XAMPP/MySQL)
# ==========================================
# El parámetro createDatabaseIfNotExist=true creará db_usuarios automáticamente si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
# Por defecto en XAMPP la contraseña está vacía
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 3. CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# Imprime las consultas SQL en la consola (muy útil para debuggear)
spring.jpa.show-sql=true
# Lo ponemos en "none" porque delegaremos la creación de tablas a Liquibase
spring.jpa.hibernate.ddl-auto=none

# ==========================================
# 4. CONFIGURACIÓN DE LIQUIBASE
# ==========================================
spring.liquibase.enabled=true
# Ruta donde crearemos el archivo con las instrucciones para crear la tabla y los 10 productos
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql

# ==========================================
# 5. EUREKA CLIENT
# ==========================================
# Por ahora lo dejamos en false para que no arroje errores en la consola 
# buscando al Gateway/Eureka Server mientras desarrollamos este servicio aislado.
# Lo cambiaremos a true en la Fase 4.
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
