spring.application.name=despacho-service

# Puerto del servicio despacho-service
server.port=9095

# Conexion a la base de datos db_despachos, si no existe se crea automaticamente
spring.datasource.url=jdbc:mysql://localhost:3306/db_despachos?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Liquibase
spring.liquibase.enabled=true
# Ruta del archivo con las instrucciones para crear la tabla y los 10 registros
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql

#Logger
logging.file.name=logs/despacho-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n